Enforce 'Debug = False' in 'native_main.py' before Git commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,6 +2,13 @@
 
 source ./scripts/common
 
+# Check if 'DEBUG = True' set in 'native_main.py'
+if [[ "$(native_main_debug_flag)" != "False" ]]; then
+  echo "- Aborting Git commit ..."
+  echo "- Set 'DEBUG = False' in 'native_main.py'"
+  exit 1
+fi
+
 jsfiles=$(cachedFiles)
 
 [ -z "$jsfiles" ] && exit 0
@@ -17,16 +24,8 @@ if [ -n "$consoleFiles" ]; then
 fi
 
 if [ -n "$uglyFiles" ]; then
-    echo "Aborting Git commit."
     echo "Prettify your files first:"
     echo 'npm run pretty'
     exit 1
 fi
 
-if [[ "$(grep \
-        -E '^.*DEBUG.*=.*True.*$' \
-        -c native/native_main.py)" == "1" ]]; then
-    echo "Aborting Git commit."
-    echo "Remove 'DEBUG = True' from 'native_main.py'"
-    exit 1
-fi
